version: '3'
services:
  atm:
    build: .

    ports:
      - "8081:8081"
    depends_on:
      - "mysql"
    environment:
      DB_URL: jdbc:mysql://localhost:3305/atm?createDatabaseIfNotExist=true
      DB_PASS: root
      DB_USR: root
  mysql:
    image: library/mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /home/victor/test/mysql:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: atm

